// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFIdbig4hcbusq18NVtg1ChZ2Ej7q0XY',
    appId: '1:778421452148:web:73a11045dd5fe1ced60021',
    messagingSenderId: '778421452148',
    projectId: 'angular-test-firebase-f11cb',
    authDomain: 'angular-test-firebase-f11cb.firebaseapp.com',
    storageBucket: 'angular-test-firebase-f11cb.appspot.com',
    measurementId: 'G-GRHL2VT9GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvwiizClWqECcQ9PtZt2ZipV5n_5MEGtg',
    appId: '1:778421452148:android:fd61383b1519d1f4d60021',
    messagingSenderId: '778421452148',
    projectId: 'angular-test-firebase-f11cb',
    storageBucket: 'angular-test-firebase-f11cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2skeFJd0dRe8ldV0M357sZHkocLbe8Y',
    appId: '1:778421452148:ios:65db599749c7e6c0d60021',
    messagingSenderId: '778421452148',
    projectId: 'angular-test-firebase-f11cb',
    storageBucket: 'angular-test-firebase-f11cb.appspot.com',
    iosBundleId: 'com.ffapp.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2skeFJd0dRe8ldV0M357sZHkocLbe8Y',
    appId: '1:778421452148:ios:65db599749c7e6c0d60021',
    messagingSenderId: '778421452148',
    projectId: 'angular-test-firebase-f11cb',
    storageBucket: 'angular-test-firebase-f11cb.appspot.com',
    iosBundleId: 'com.ffapp.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRFIdbig4hcbusq18NVtg1ChZ2Ej7q0XY',
    appId: '1:778421452148:web:73a11045dd5fe1ced60021',
    messagingSenderId: '778421452148',
    projectId: 'angular-test-firebase-f11cb',
    authDomain: 'angular-test-firebase-f11cb.firebaseapp.com',
    storageBucket: 'angular-test-firebase-f11cb.appspot.com',
    measurementId: 'G-GRHL2VT9GH',
  );

}